apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: swai-eks-cluster
  version: "1.30"
  region: ap-northeast-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  subnets:
    public:
      ap-northeast-2a: { id: public_a }
      ap-northeast-2b: { id: public_b }
      ap-northeast-2c: { id: public_c }
    private:
      ap-northeast-2a: { id: private_a }
      ap-northeast-2b: { id: private_b }
      ap-northeast-2c: { id: private_c }

managedNodeGroups:
  - name: swai-web-ng
    labels: { swai/deployed: deploy }
    instanceName: swai-web-svc
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 8
    privateNetworking: true