apiVersion: apps/v1
kind: Deployment
metadata:
  name: swai-dpm
  namespace: swai-ns
  labels:
    swai/deployed: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      swai/deployed: deploy
  template:
    metadata:
      labels:
        swai/deployed: deploy
    spec:
      containers:
      - image: IMAGE
        name: swai-container
        ports:
        - containerPort: 8080
  strategy:
    type: Recreate