apiVersion: apps/v1
kind: Deployment
metadata:
  name: swai-dpm
  namespace: swai-ns
  labels:
    swai/deployed: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      swai/deployed: deploy
  template:
    metadata:
      labels:
        swai/deployed: deploy
    spec:
      containers:
      - image: IMAGE
        name: swai-container
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "<RDS-ENDPOINT>"
        - name: DB_NAME
          value: "<DB_NAME>"
        - name: DB_USER
          value: "<DB_USER>"
        - name: DB_PASSWORD
          value: "<DB_PASSWORD>"
        - name: JWT_SECRET
          value: "<JWT_SECRET>"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: S3_BUCKET_NAME
          value: "<S3_BUCKET_NAME>"
  strategy:
    type: Recreate