apiVersion: v1
kind: Service
metadata:
  name: swai-svc
  namespace: swai-ns
spec:
  selector:
    swai/deployed: deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort